{
    "name": "Real Estate",
    "version": "1.0",
    "summary": "Real Estate Management Module",
    "description": "A module to manage real estate properties, agents, and sales.",
    "author": "Sultan",
    "depends": ["base", "account"],
    "installable": True,
    "application": True,
    "category": "Real Estate/Brokerage",
    "data": [
        "security/estate_security.xml",
        "security/ir.model.access.csv",
        "data/estate.property.type.csv",
        "data/estate_data.xml",
        "data/estate_property_demo_extension_data.xml",
        "report/estate_property_offer_table_template.xml",
        "report/estate_property_template.xml",
        "report/estate_property_invoice_template.xml",
        "report/user_properties_template.xml",
        "report/estate_property_report.xml",
        "report/estate_property_invoice_report.xml",
        "report/user_properties_report.xml",
        "views/estate_property_offer_views.xml",
        "views/estate_property_type_views.xml",
        "views/estate_property_tag_views.xml",
        "views/estate_property_views.xml",
        "views/res_users_views.xml",
        "views/estate_menus.xml",
    ],
}